import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Theme } from "@/types/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Simulate database fetch like in the subject project
async function getSiteData(): Promise<{ themeName: string }> {
  // Simulate async database call
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        themeName: Math.random() > 0.5 ? "one" : "two"
      });
    }, 100);
  });
}

function toKebabCase(str: string) {
  return str.toLowerCase().replace(/\s+/g, '-');
}

export default async function RootLayout() {
  // Mimic the subject project's pattern exactly
  const site = await getSiteData();
  const themeName = site?.themeName ? toKebabCase(site?.themeName) : "one";

  const selectedTheme = await import(`@/styles/themes/theme-${themeName}/theme-${themeName}`);

  console.log(themeName);
  console.log(selectedTheme);

  const theme = (selectedTheme.default as Theme) ?? null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center justify-center h-screen w-screen">
          <h1 className="text-9xl">{theme.name}</h1>
        </div>
      </body>
    </html>
  );
}
