import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          className={`flex items-center justify-center h-screen w-screen ${inter.className}`}
        >
          <div className="flex flex-col gap-4">
            <h1>Root Layout</h1>
            <div className="flex gap-4">
              <Link href="http://site-one.localhost:3000/" className="rounded-full bg-primary text-primary-foreground px-4 py-2">Site One</Link>
              <Link href="http://site-two.localhost:3000/" className="rounded-full bg-primary text-primary-foreground px-4 py-2">Site Two</Link>
            </div>
            {children}
          </div>
          
        </div>
      </body>
    </html>
  );
}
