import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function delayedThemeName() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve("one");
    }, 1000);
  });
}

export default async function RootLayout() {
  const themeName = await delayedThemeName();

  const selectedTheme = await import(`@/themes/theme-${themeName}`);

  const theme = selectedTheme.default ?? null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center justify-center h-screen w-screen">
          <h1 className="text-9xl">{theme.themeName}</h1>
        </div>
      </body>
    </html>
  );
}
